name: Deploy EKS App

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout repo
      - name: Checkout
        uses: actions/checkout@v5

      # 2️⃣ Configure AWS credentials
      - name: Configure AWS
        uses: aws-actions/configure-aws-credentials@v5
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1

      # 3️⃣ Setup Terraform
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v4

      # 4️⃣ Terraform Init
      - name: Terraform Init
        run: terraform init
        working-directory: terraform

      # 5️⃣ Terraform Apply (creates VPC + EKS + Node Group)
      - name: Terraform Apply
        run: terraform apply -auto-approve
        working-directory: terraform

      # 6️⃣ Configure kubectl dynamically and wait for nodes
      - name: Configure kubectl and wait for nodes
        run: |
          CLUSTER_NAME=$(terraform output -raw cluster_name)
          echo "Using cluster: $CLUSTER_NAME"
          aws eks update-kubeconfig --name $CLUSTER_NAME --region ap-south-1
          echo "Waiting for all nodes to be ready..."
          kubectl wait --for=condition=Ready nodes --all --timeout=600s
        working-directory: terraform

      # 7️⃣ Deploy nginx Kubernetes app
      - name: Deploy Kubernetes App
        run: |
          kubectl apply -f k8s/deployment.yaml
          kubectl apply -f k8s/service.yaml

      # 8️⃣ Output LoadBalancer URL
      - name: Get nginx Service URL
        run: |
          echo "Waiting for LoadBalancer IP..."
          kubectl wait --for=condition=available --timeout=300s svc/nginx-service
          kubectl get svc nginx-service -o jsonpath='{.status.loadBalancer.ingress[0].hostname}'
